# Generated by Django 5.0.6 on 2024-05-26 21:48

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('local_create_date', models.DateTimeField(auto_now=True)),
                ('local_update_date', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('text', models.TextField()),
                ('picture', models.ImageField(default='', upload_to='articles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('local_create_date', models.DateTimeField(auto_now=True)),
                ('local_update_date', models.DateTimeField(auto_now=True)),
                ('logo', models.CharField(max_length=20)),
                ('bio', models.TextField()),
                ('requisites', models.TextField()),
                ('date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('local_create_date', models.DateTimeField(auto_now=True)),
                ('local_update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=10)),
                ('discount', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(100)])),
                ('end_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('local_create_date', models.DateTimeField(auto_now=True)),
                ('local_update_date', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Projectile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('local_create_date', models.DateTimeField(auto_now=True)),
                ('local_update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='enter name of projectile(гиря тд тп)', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('local_create_date', models.DateTimeField(auto_now=True)),
                ('local_update_date', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('grade', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('local_create_date', models.DateTimeField(auto_now=True)),
                ('local_update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('salary', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('local_create_date', models.DateTimeField(auto_now=True)),
                ('local_update_date', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(default=datetime.date(2024, 5, 26))),
                ('phone_number', models.CharField(blank=True, max_length=19, null=True, validators=[django.core.validators.RegexValidator(message='+375 (29) XXX-XX-XX;   ', regex='\\+\\d{3} \\(\\d{2}\\) \\d{3}-\\d{2}-\\d{2}$')])),
                ('costs', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('local_create_date', models.DateTimeField(auto_now=True)),
                ('local_update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('discount', models.PositiveSmallIntegerField()),
                ('exp_date', models.DateField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entities.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('local_create_date', models.DateTimeField(auto_now=True)),
                ('local_update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('all_price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_services', models.PositiveSmallIntegerField(default=10)),
                ('max_clients', models.PositiveSmallIntegerField(default=10)),
                ('is_open', models.BooleanField(default=False)),
                ('is_edit', models.BooleanField(default=True)),
                ('clients', models.ManyToManyField(blank=True, to='entities.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('local_create_date', models.DateTimeField(auto_now=True)),
                ('local_update_date', models.DateTimeField(auto_now=True)),
                ('hall_name', models.CharField(help_text='enter hall name', max_length=20)),
                ('projectiles', models.ManyToManyField(help_text='select projectiles for this hall', to='entities.projectile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('local_create_date', models.DateTimeField(auto_now=True)),
                ('local_update_date', models.DateTimeField(auto_now=True)),
                ('info', models.TextField()),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entities.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('local_create_date', models.DateTimeField(auto_now=True)),
                ('local_update_date', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('typeOfservice', models.CharField(default='Gym', max_length=100)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.group')),
                ('hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.hall')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('local_create_date', models.DateTimeField(auto_now=True)),
                ('local_update_date', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=19, null=True, validators=[django.core.validators.RegexValidator(message='+375 (29) XXX-XX-XX;   ', regex='\\+\\d{3} \\(\\d{2}\\) \\d{3}-\\d{2}-\\d{2}$')])),
                ('bio', models.TextField(default=None, null=True)),
                ('photo', models.ImageField(default='', upload_to='instructors/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('services', models.ManyToManyField(to='entities.service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
